---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: invite-activity-config
  namespace: growth
spec:
  encryptedData:
    config.json: AgCZZqTA22bOAZecHeeipam5Cfa3XWqlvFnf2l37x0ynGpBZsYmRj1nYZsloivV9D2dweRI6bndzHMDxOsrNhL6z+Ta9paNfPNTiKU4a3mmbDLNGp4a12/7qdSGczSRRTTTp0zRkHfRDavyofFR0vSL+biolKDQB0rD+6KuJaBLS66M66TUb8OiD9XkSBNBQuOFU0xI2NVF8/FIu5N484nh5OJ7X6KMg3hEkUmnZ+bE0/3CrLy0sFuGqbuj36eL1epo2A0x/8nCZOQ5L3/3jhYnX9bf3zRBrOaHmbIpf5PObtXkOqDWIW8kOmCbzf/PFMF6TgtQBBRpVlaJE4Sswo6kI6SqgtosC6UBemX1mXFcuIkAgUfymCtb87ZPPhbipsGq4hlyPijrIZyp1xAYwtVbdT7/v4sIXUN18qg7DAS8AOQRGlOdcHK4hfV++71T65aHFPJx0CUXCq0kCHp44DZwHWOhGiJffqkQznxYvehNPtq0jgoELXvsuYnUXthB3fUX0qOMu0Pw6s7xKyw1u41vMMQfiY8IHm6H3Dg8tnusRFVOvFFcdw6vDWKuJWPRpCl/MK4e40bkMFC5fk5yCiE0qsqOrUqYPrB82iQBs4aLRMfDI8mPgIkbI8aqWqtPcfxQZqHL/WJe2ojmnGJQ7yc84vRT6NNhpDDKeeuaCdBiaXZeJJ+x8X+6rmP87A+PKJSUYJDiEnfjPHFTEOG+wti+4AhIW8v9B4dcDdl0JfEm+PIbbM8FxlIwmyQ15J9OgzM15qL8RtgSncG0RP/uFG7DOpJ5CTmHRq9yUmw2JjrVEjZNIwbv071jhw5oX19KenizKMVXHFVgoLXu8oQIkz4S2ndpv57wv2YSpbc5JkhndKNlUUbBthdV1N1kmQDXRnOIreyv6K/OcbqrkLBFuvGErFmR38658OmReiSmv
  template:
    metadata:
      labels:
        app.kubernetes.io/name: invite-activity
      name: invite-activity-config
      namespace: growth
    type: Opaque
